# Generated by Django 5.0.4 on 2024-05-24 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
