# Generated by Django 5.0.6 on 2024-05-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_prerequisite_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='required_courses',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_for', to='registration.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='prerequisite_course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='registration.course'),
            preserve_default=False,
        ),
    ]
