# Generated by Django 5.0.6 on 2024-05-28 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_coursereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
